[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_raffle = "GFkrs8CmUsviDmAgQRBuj9grwHe5jqKCGjmsuV8CBH7L"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./local-deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
program = "./local-deploy/mpl_token_auth_rules.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/tests/**/*.spec.ts"